# Generated by Django 5.0.3 on 2024-05-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcels_geometry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parcels',
            new_name='Parcel',
        ),
    ]
