# Generated by Django 5.0.3 on 2024-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_alter_parcel_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='area_sf',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='building_f',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='density',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='gfa_sf',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='height_m',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='proj_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sold_per',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='storey',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='units',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
