# Generated by Django 5.0.3 on 2024-05-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_alter_parcel_address_alter_parcel_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='type',
            new_name='parcel_type',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='storey',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
