# Generated by Django 5.0.3 on 2024-05-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_rename_type_parcel_parcel_type_alter_parcel_storey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='storey',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
